version: "3.5"
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/api.knigopis.com
      - /var/repo.knigopis.com:/var/repo.knigopis.com
    working_dir: /api.knigopis.com
    restart: always
    networks:
      - default
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./public:/api.knigopis.com/public
    networks:
      - default
      - nginx-proxy
    restart: always
    environment:
      HTTPS_METHOD: "noredirect"
      VIRTUAL_HOST: "api.knigopis.com"
      LETSENCRYPT_HOST: "api.knigopis.com"

networks:
  nginx-proxy:
    external: true
