### Register
POST {{host}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "newuser7",
  "password": "securepassword",
  "lang": "ru"
}

>> ./responses/reg-{{$timestamp}}.json

### Register error
POST {{host}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "a",
  "password": "b",
  "lang": "ru"
}

>> ./responses/reg-er-{{$timestamp}}.json


### Login
POST {{host}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "newuser5",
  "password": "securepassword",
  "lang": "ru"
}

>> ./responses/login-{{$timestamp}}.json

### Logout
POST {{host}}/auth/logout
Content-Type: application/json
Accept: application/json

>> ./responses/logout-{{$timestamp}}.json
